#+TITLE: Plan for zsh-history
#+STARTUP: showall

* Subcommand 'merge'
    Merge two histories, optionally dedup as well

    zsh-history merge [--dedup] hist1 hist2 > hist3

* Subcommand 'format'
  Output history in various format, including zsh format.
  Allow transformations like dedup and sort before output.

** Option 'dedup'
    Remove duplicate commands, keeping the newest instances of each;
    optionally moving the old command into a backup file.

    What is the 'newest' instance?
    There are two orders:
    - file order, entries in the order as the appear in the file
    - timestamp order, entries sorted by timestamps
    In well-formed files those should be (roughly) the same.

    We use:
    - file order by default (keep the one that appears latest in file)
    - timestamp order if --sort is also given.
    (so: effectively it's like doing --sort first and then --dedup)

    zsh-history dedup hist1 > hist2
    zsh-history dedup --in-place histfile

** Option 'sort'
    Sort history by timestamp
    Since timestamp resolution is only 1s, be careful to use a stable sort.
